---
hero_image: images/banner.png
listed: true
title: Gebruikersnaam generator
description: Genereer geweldige gebruikersnamen die je online kunt gebruiken
version: 4
last_tested: 2018/03/11
steps:
  - 
    title: Inleiding
  - 
    title: Gebruikersnamen genereren
    completion:
      - engaged
  - 
    title: 'Uitdaging: voeg meer variatie toe'
    challenge: true
  - 
    title: Je favoriete gebruikersnamen opslaan
  - 
    title: 'Uitdaging: voeg een getal toe'
    challenge: true
  - 
    title: 'Uitdaging: maak een profielfoto'
    challenge: true
    completion:
      - internal
  - 
    title: What can you do now?
    completion:
      - external
