---
hero_image: images/banner.png
listed: true
title: Username generator
description: Generate awesome usernames that you can use online
version: 4
last_tested: 2018-03-11
steps:
- title: Introduction
  completion: engaged
- title: Generating usernames
- title: 'Challenge: add more variety'
  challenge: true
  completion: internal
- title: Saving your favourite usernames
- title: 'Challenge: add a number'
  challenge: true
- title: 'Challenge: create your profile picture'
  challenge: true
- title: What next?
