---
hero_image: images/banner.png
listed: true
title: Benutzernamen Generator
description: Generiere fantastische Benutzernamen, die Du online verwenden kannst
version: 4
last_tested: 2018-03-11
steps:
  - 
    title: Einleitung
  - 
    title: Benutzernamen generieren
    completion:
      - engaged
  - 
    title: 'Herausforderung: mehr Abwechslung hinzufügen'
    challenge: true
  - 
    title: Speichere Deine bevorzugten Benutzernamen
  - 
    title: 'Herausforderung: Füge eine Nummer hinzu'
    challenge: true
  - 
    title: 'Herausforderung: Erstelle Dein Profilbild'
    challenge: true
    completion:
      - internal
  - 
    title: What can you do now?
    completion:
      - external
