---
hero_image: images/banner.png
listed: true
title: Benutzernamen Generator
description: Generiere fantastische Benutzernamen, die Du online verwenden kannst
version: 4
last_tested: 2018-03-11
steps:
- title: Einleitung
- title: Benutzernamen generieren
- title: 'Herausforderung: mehr Abwechslung hinzufügen'
  challenge: true
- title: Speichere Deine bevorzugten Benutzernamen
  completion:
  - engaged
  - internal
- title: 'Herausforderung: Füge eine Nummer hinzu'
  challenge: true
- title: 'Herausforderung: Erstelle dein Profilbild'
  challenge: true