---
hero_image: images/banner.png
listed: true
title: Gerador de nome de usuário
description: Gere nomes de usuário incríveis que você pode usar online
version: 4
last_tested: 2018-03-11
steps:
  - 
    title: Introdução
  - 
    title: Gerando nomes de usuário
  - 
    title: 'Desafio: adicione mais variedade'
    challenge: true
  - 
    title: Salvando seus nomes de usuário favoritos
    completion:
      - engaged
      - internal
  - 
    title: 'Desafio: adicione um número'
    challenge: true
  - 
    title: 'Desafio: crie sua foto do perfil'
    challenge: true
  - 
    title: E agora?
