---
hero_image: images/banner.png
listed: true
title: 用戶名生成器
description: 創建一個可以在線使用的用戶名
version: 4
last_tested: 2018-03-11
steps:
  - 
    title: 介紹
  - 
    title: 創建用戶名
  - 
    title: "挑戰：添加多樣化"
    challenge: true
  - 
    title: 保存您喜歡的用戶名
  - 
    title: "挑戰：加入數字"
    challenge: true
  - 
    title: "挑戰：創建您的個人資料照片"
    challenge: true
  - 
    title: '下一步是什麼？'
