---
hero_image: images/banner.png
listed: true
title: 사용자 이름 생성기
description: 온라인에서 사용할 수 있는 멋진 사용자명 만들기
version: 4
last_tested: 2018-03-11
steps:
  - 
    title: 소개
  - 
    title: 사용자명 만들기
  - 
    title: '도전과제: 변수 더 추가하기'
    challenge: true
  - 
    title: 가장 좋아하는 사용자명 저장하기
    completion:
      - engaged
      - internal
  - 
    title: '도전과제: 숫자 추가하기'
    challenge: true
  - 
    title: '도전과제: 프로필 사진 만들기'
    challenge: true
  - 
    title: 더 나아가기
